name: Kernel Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Execute Permission for build.sh
      run: chmod +x build.sh

    - name: Run build.sh Script
      run: ./build.sh
