name: Build Kernel with KernelSU Next

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile Kernel and Package with AnyKernel3

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set Up Environment Variables
      run: |
        echo "KERNEL_DEFCONFIG=gauguin_defconfig" >> $GITHUB_ENV
        echo "ANYKERNEL_DIR=$GITHUB_WORKSPACE/AnyKernel3" >> $GITHUB_ENV
        echo "CLANG_DIR=$GITHUB_WORKSPACE/clang" >> $GITHUB_ENV
        echo "IMAGE=$GITHUB_WORKSPACE/out/arch/arm64/boot/Image.gz-dtb" >> $GITHUB_ENV

    - name: Clone Clang Toolchain
      run: |
        git clone --depth=1 https://github.com/llvm/llvm-project.git $CLANG_DIR

    - name: Build Kernel
      run: |
        export PATH=$CLANG_DIR/bin:$PATH
        make O=out ARCH=arm64 $KERNEL_DEFCONFIG
        make -j$(nproc) O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-

    - name: Package Kernel with AnyKernel3
      run: |
        cp $IMAGE $ANYKERNEL_DIR/
        cd $ANYKERNEL_DIR
        zip -r9 KernelSU-Next-Gauguin.zip ./*

    - name: Upload Flashable Zip
      uses: actions/upload-artifact@v3
      with:
        name: KernelSU-Next-Gauguin
        path: ${{ env.ANYKERNEL_DIR }}/KernelSU-Next-Gauguin.zip
